### ISSUE TITLE
Picker error. Attempted to set a key on an object that is meant to be immutable.

### ISSUE THREAD

**Issue by markterence** [bietkul/react-native-form-builder#16]
Error : You attempted to set the key `backgroundcolor` with the value `"transparent"`
on an object that is meant to be immutables and has been frozen.  

![image](https://user-images.githubusercontent.com/2003215/40348718-0d445512-5dd7-11e8-95a8-9bfbf5a3ae1c.png)
![image](https://user-images.githubusercontent.com/2003215/40348739-1a1bd0f8-5dd7-11e8-850f-6703d0aaef2e.png)

```
"react": "16.3.1",
"react-native": "0.55.3",
"native-base": "^2.4.2",
"babel-jest": "22.4.3",
"babel-preset-react-native": "4.0.0",
"jest": "22.4.3",
"react-test-renderer": "16.3.1"
```

#### Environment:
  OS: Windows 7
  Node: 8.9.1
  Yarn: Not Found
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003
 
#### Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

#### Android Device
 Android version: Android 5.1.1

**Comment by amed** [comment]
This issue seems to happen again:

`react@16.3.1`
`react-native@0.55.4`
`react-native-form-builder@^1.0.15`
