### ISSUE TITLE
Merge Error Background Color

### ISSUE THREAD

**Issue by ajiehatajie** [bietkul/react-native-form-builder#18]
please merge to brach master

[link](https://github.com/bietkul/react-native-form-builder/commit/4bf0d1c8809822d4582f1cf458ffc28406ea013a)
   
           <View style={{...styles.pickerMainAndroid, ...{
            backgroundColor: theme.pickerBgColor,
            borderBottomColor: theme.inputBorderColor,
            borderBottomWidth: theme.borderWidth,   
        }}}>
`

thanks in advance

**Comment by bietkul** [comment]
It's done
