### ISSUE TITLE
Custom components are not getting rendered in the form - Phone Input

### ISSUE THREAD

**Issue by ami0011** [bietkul/react-native-form-builder#26]
I am trying to integrate phone input via customComponents prop. Here is the code. Any help would be appreciated.
`{
        type: "custom",
        name: 'phone',
        required: true,
        label: 'Phone',
        editable: true,
        props: {},
        customComponents : { custom: {component:PhoneInputComponent}}
    }`

version ---> react-native-form-builder : 1.0.15

anyone have any idea about this, please help.

**Comment by luissmg** [comment]
Did you read the docs properly? I think you are setting this wrong. Can you share a bit more of code?
