### ISSUE TITLE
PropTypes has move to its own package starting React 15.5

### ISSUE THREAD

**Issue by alterx** [bietkul/react-native-form-builder#8]
PropTypes has moved into it's own package starting with React 15.5+ (https://reactjs.org/blog/2017/04/07/react-v15.5.0.html) so this package is throwing of errors when used with newer versions of React (16, for example).

Change should be pretty straightforward: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactproptypes

Are you accepting PRs?

**Comment by bietkul** [comment]
Yes, It'll be best if you can contribute.

**Comment by bietkul** [comment]
Thanks I've merged it and updated the package on npm also.

**Comment by alterx** [comment]
Perfect @bietkul , thank you :)
